import type { NextPage } from "next";
import Head from "next/head";
import React, { useState } from "react";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const [username, setUsername] = useState<string>();
  const createUser = trpc.useMutation("user.createUser");

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (!username) return;
    // Invoke tRPC mutation
    await createUser.mutateAsync({
      name: username,
    });
  };

  const handleSetUsername = (e: React.ChangeEvent<HTMLInputElement>) => {
    setUsername(e.target.value);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col gap-4 items-center justify-center min-h-screen p-4">
        <h1 className="text-4xl leading-normal font-extrabold text-gray-700">
          Welcome to the <span className="text-blue-300">T3</span> Chatroom
        </h1>
        <form className="flex flex-col gap-4" onSubmit={handleSubmit}>
          <input
            onChange={handleSetUsername}
            className="p-2 text-xl border rounded-sm"
            placeholder="Username"
          />
          <button
            className="text-xl m-2 bg-blue-300 hover:bg-blue-200
          p-2 rounded text-white"
          >
            Sign In
          </button>
        </form>
      </main>
    </>
  );
};

export default Home;
