import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useContext, useState } from "react";
import { Button, Variant } from "../components/Button";
import { UserContext } from "../context/UserContext";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const [username, setUsername] = useState<string>();
  const { setUser } = useContext(UserContext);
  const createUser = trpc.useMutation("user.createUser");
  const router = useRouter();

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (!username) return;
    // Invoke tRPC mutation
    const myUser = await createUser.mutateAsync({
      name: username,
    });

    // 1. Save user id in global state (with context?)
    setUser(myUser);
    router.push("/dashboard");
  };

  const handleSetUsername = (e: React.ChangeEvent<HTMLInputElement>) => {
    setUsername(e.target.value);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col gap-4 items-center justify-center min-h-screen p-4">
        <h1 className="text-4xl leading-normal font-extrabold text-gray-700">
          Welcome to the <span className="text-blue-300">T3</span> Chatroom
        </h1>
        <form className="flex flex-col gap-4" onSubmit={handleSubmit}>
          <input
            value={username}
            onChange={handleSetUsername}
            className="p-2 text-xl border rounded-sm"
            placeholder="Username"
          />
          <Button variant={Variant.Primary}> Sign In </Button>
        </form>
      </main>
    </>
  );
};

export default Home;
